### ISSUE TITLE
Add native chat interface

### ISSUE THREAD

**Issue by tubbo** [waxpoetic/brotherly#24]
Although we'll have live chat on most of the services that we integrate with, it would be nice to host our own implementation of a live chat, as we'll have more control over its look and feel as well as its longevity. An efficient implementation of a chat system requires some kind of WebSocket interface to the browser, which is why this issue will require an upgrade to Rails 5.

**Tasks:**
- [x] Upgrade Rails to latest 5.0.0 release
- [x] Implement ActionCable channel for live chat
- [x] Only show live chat when an episode is currently broadcasting
- [ ] Create UI for live chat interface next to the episode

**Comment by tubbo** [comment]
still working on the UI for this but got most of the backend completed. also waiting to deploy this until rails 5.0 hits.
