### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by tubbo** [waxpoetic/brotherly#29]
Now that it's out, we'll need this to complete #24 and get all the nice ActiveRecord speed benefits.

## Tasks

- [x] Replace draper with [makeover](https://github.com/tubbo/makeover)
- [x] Upgrade ControllerResources
- [x] Upgrade gems and run Rails upgrade tasks
- [ ] Fix any broken tests
