### ISSUE TITLE
Block public access to staging server

### ISSUE THREAD

**Issue by tubbo** [waxpoetic/brotherly#40]
The staging server should be protected, both from crawling search engines and accidental social media shares. To do this, we will implement HTTP Basic Auth on the staging server, with a repo-stored username and password. In addition, the **public/robots.txt** file will be removed and dynamically generated via a Rails route. This is to block all spiders from crawling http://beta.brother.ly, but allow crawling of the production site.
### Tasks
- [x] Implement `Rack::Auth::Basic` middleware with username **brotherly** and password **l0v3** on the staging server
- [x] Create controller for rendering current robots.txt file as `text/plain`
- [x] Update robots.txt route to block all spiders when requested from the staging server
